sonar.projectKey=Unitime
sonar.projectName=UniTime
sonar.sources=JavaSource
sonar.java.binaries=target/classes
sonar.java.source=17
sonar.host.url=http://localhost:9000
sonar.token=sqa_9e2d886b75ec1fd8d3d7ed21e06721656be6eac5